# Generated by Django 4.0.4 on 2022-06-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siphi_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='minutes',
            new_name='mnts',
        ),
    ]
