# Generated by Django 4.0.4 on 2022-05-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siphi_project', '0002_movieimage_alter_role_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default='none', max_length=5000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
