# Generated by Django 4.0.4 on 2022-06-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siphi_project', '0002_rename_minutes_movie_mnts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mnts',
            field=models.CharField(blank=True, default='60', max_length=128, null=True),
        ),
    ]
