# Generated by Django 4.0.4 on 2022-05-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siphi_project', '0004_alter_movie_description_alter_movie_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieImage',
        ),
    ]
