# Generated by Django 4.0.4 on 2022-05-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siphi_project', '0005_delete_movieimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
