# Generated by Django 4.0.4 on 2022-05-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siphi_project', '0006_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('rating', models.IntegerField(choices=[(0, 'NR - Not Rate'), (1, 'G - General Audiences'), (2, 'PG – Parental Guidance Suggested'), (3, 'PG-13 – Parents Strongly Cautioned'), (4, 'R – Restricted'), (5, 'NC-17 – Adults Only')], default=0)),
                ('category', models.CharField(choices=[('C', 'Comedy'), ('A', 'Action'), ('D', 'Drama'), ('H', 'Horror')], max_length=1, null=True)),
                ('status', models.CharField(choices=[('RA', 'recently-added'), ('MW', 'most-watched'), ('TR', 'top-rated')], max_length=2, null=True)),
                ('year_of_release', models.DateField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
