# Generated by Django 4.0.4 on 2022-05-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siphi_project', '0009_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
